name: CI-BudgetManager
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.XIEYU }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.XIEYU }}
    - run: |
        git subtree add -P packages/BudgetManager https://github.com/wanshikaimo/sub master --squash
        git subtree pull -P /packages/BudgetManager --squash https://github.com/wanshikaimo/sub master
        

    
